package com.sdg.util;

public enum MethodsList {
	getPrivileges,
	checkUsernameExists,
	getUsers,
	getUserDetails,
	getTrackerTypes,
	getSensorDataTypes,
	getTrackers,
	getTrackerDetails,
	getWildLife,
	getVehicles,
	getPeople,
	getOther,
	getPredefinedReports,
	getCustomReports,
	emailReport,
	openReport,
	sendPasswordRequest,
	user,
	animal,
	vehicle,
	person,
	other,
	tracker,
	customReport,
	authenticate,
	getCommands,
	sendConfigurationRequest,
	getPendingRequests,
	rejectRequests,
	acceptRequests,
	getObjectsWithDetails,
	getObjectsList,
	getTrackerIMEI,
	getCategory
}
